import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Copy, Download, FileCode } from "lucide-react";

export default function TerraformGenerator() {
  const [projectId, setProjectId] = useState("");
  const [region, setRegion] = useState("us-central1");
  const [resources, setResources] = useState({
    vpc: false,
    gke: false,
    sql: false,
    loadBalancer: false,
    serviceAccount: false,
  });
  const [generatedCode, setGeneratedCode] = useState("");

  const generateTerraform = () => {
    if (!projectId) {
      toast.error("Please enter a project ID");
      return;
    }

    const selectedResources = Object.entries(resources)
      .filter(([_, selected]) => selected)
      .map(([key]) => key);

    if (selectedResources.length === 0) {
      toast.error("Please select at least one resource");
      return;
    }

    let code = `# Terraform configuration for GCP project: ${projectId}
# Generated by DevOps Automation Hub

terraform {
  required_version = ">= 1.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = "${projectId}"
  region  = "${region}"
}

`;

    if (resources.vpc) {
      code += `# VPC Network
resource "google_compute_network" "vpc_network" {
  name                    = "${projectId}-vpc"
  auto_create_subnetworks = false
  routing_mode            = "REGIONAL"
}

resource "google_compute_subnetwork" "subnet" {
  name          = "${projectId}-subnet"
  ip_cidr_range = "10.0.0.0/24"
  region        = var.region
  network       = google_compute_network.vpc_network.id
  
  secondary_ip_range {
    range_name    = "pods"
    ip_cidr_range = "10.1.0.0/16"
  }
  
  secondary_ip_range {
    range_name    = "services"
    ip_cidr_range = "10.2.0.0/16"
  }
}

`;
    }

    if (resources.gke) {
      code += `# GKE Cluster
resource "google_container_cluster" "primary" {
  name     = "${projectId}-gke"
  location = var.region
  
  remove_default_node_pool = true
  initial_node_count       = 1
  
  network    = google_compute_network.vpc_network.name
  subnetwork = google_compute_subnetwork.subnet.name
  
  ip_allocation_policy {
    cluster_secondary_range_name  = "pods"
    services_secondary_range_name = "services"
  }
  
  workload_identity_config {
    workload_pool = "${projectId}.svc.id.goog"
  }
}

resource "google_container_node_pool" "primary_nodes" {
  name       = "primary-node-pool"
  location   = var.region
  cluster    = google_container_cluster.primary.name
  node_count = 2
  
  autoscaling {
    min_node_count = 1
    max_node_count = 5
  }
  
  node_config {
    machine_type = "e2-medium"
    disk_size_gb = 50
    
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
    
    workload_metadata_config {
      mode = "GKE_METADATA"
    }
  }
}

`;
    }

    if (resources.sql) {
      code += `# Cloud SQL PostgreSQL
resource "google_sql_database_instance" "postgres" {
  name             = "${projectId}-postgres"
  database_version = "POSTGRES_15"
  region           = var.region
  
  settings {
    tier              = "db-f1-micro"
    availability_type = "ZONAL"
    disk_size         = 10
    
    backup_configuration {
      enabled            = true
      start_time         = "03:00"
      point_in_time_recovery_enabled = true
    }
    
    ip_configuration {
      ipv4_enabled = false
      private_network = google_compute_network.vpc_network.id
    }
  }
  
  deletion_protection = false
}

resource "google_sql_database" "database" {
  name     = "app_db"
  instance = google_sql_database_instance.postgres.name
}

`;
    }

    if (resources.loadBalancer) {
      code += `# Global HTTP(S) Load Balancer
resource "google_compute_global_address" "lb_ip" {
  name = "${projectId}-lb-ip"
}

resource "google_compute_backend_service" "backend" {
  name          = "${projectId}-backend"
  protocol      = "HTTP"
  timeout_sec   = 30
  health_checks = [google_compute_health_check.health.id]
}

resource "google_compute_health_check" "health" {
  name               = "${projectId}-health-check"
  check_interval_sec = 10
  timeout_sec        = 5
  
  http_health_check {
    port         = 80
    request_path = "/health"
  }
}

`;
    }

    if (resources.serviceAccount) {
      code += `# Service Account
resource "google_service_account" "app_sa" {
  account_id   = "${projectId}-app-sa"
  display_name = "Application Service Account"
}

resource "google_project_iam_member" "app_sa_roles" {
  for_each = toset([
    "roles/storage.objectViewer",
    "roles/cloudsql.client",
    "roles/logging.logWriter",
  ])
  
  project = var.project_id
  role    = each.value
  member  = "serviceAccount:\${google_service_account.app_sa.email}"
}

`;
    }

    code += `# Variables
variable "project_id" {
  description = "GCP Project ID"
  type        = string
  default     = "${projectId}"
}

variable "region" {
  description = "GCP Region"
  type        = string
  default     = "${region}"
}

# Outputs
output "project_id" {
  value = var.project_id
}

output "region" {
  value = var.region
}
`;

    setGeneratedCode(code);
    toast.success("Terraform configuration generated!");
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedCode);
    toast.success("Copied to clipboard!");
  };

  const downloadFile = () => {
    const blob = new Blob([generatedCode], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "main.tf";
    a.click();
    toast.success("File downloaded!");
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-foreground">Terraform Generator</h1>
        <p className="mt-2 text-muted-foreground">
          Generate production-ready Terraform configurations for GCP infrastructure
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Configuration Form */}
        <Card>
          <CardHeader>
            <CardTitle>Configuration</CardTitle>
            <CardDescription>Select resources and configure your infrastructure</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-2">
              <Label htmlFor="projectId">GCP Project ID</Label>
              <Input
                id="projectId"
                placeholder="my-gcp-project"
                value={projectId}
                onChange={(e) => setProjectId(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="region">Region</Label>
              <Input
                id="region"
                placeholder="us-central1"
                value={region}
                onChange={(e) => setRegion(e.target.value)}
              />
            </div>

            <div className="space-y-4">
              <Label>Resources to Generate</Label>
              
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="vpc"
                  checked={resources.vpc}
                  onCheckedChange={(checked) =>
                    setResources({ ...resources, vpc: checked as boolean })
                  }
                />
                <label htmlFor="vpc" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  VPC Network with Subnets
                </label>
              </div>

              <div className="flex items-center space-x-2">
                <Checkbox
                  id="gke"
                  checked={resources.gke}
                  onCheckedChange={(checked) =>
                    setResources({ ...resources, gke: checked as boolean })
                  }
                />
                <label htmlFor="gke" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  GKE Cluster with Node Pool
                </label>
              </div>

              <div className="flex items-center space-x-2">
                <Checkbox
                  id="sql"
                  checked={resources.sql}
                  onCheckedChange={(checked) =>
                    setResources({ ...resources, sql: checked as boolean })
                  }
                />
                <label htmlFor="sql" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  Cloud SQL PostgreSQL
                </label>
              </div>

              <div className="flex items-center space-x-2">
                <Checkbox
                  id="loadBalancer"
                  checked={resources.loadBalancer}
                  onCheckedChange={(checked) =>
                    setResources({ ...resources, loadBalancer: checked as boolean })
                  }
                />
                <label htmlFor="loadBalancer" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  Global Load Balancer
                </label>
              </div>

              <div className="flex items-center space-x-2">
                <Checkbox
                  id="serviceAccount"
                  checked={resources.serviceAccount}
                  onCheckedChange={(checked) =>
                    setResources({ ...resources, serviceAccount: checked as boolean })
                  }
                />
                <label htmlFor="serviceAccount" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  Service Account with IAM
                </label>
              </div>
            </div>

            <Button onClick={generateTerraform} className="w-full">
              <FileCode className="mr-2 h-4 w-4" />
              Generate Terraform Code
            </Button>
          </CardContent>
        </Card>

        {/* Generated Code */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Generated Code</CardTitle>
                <CardDescription>Your Terraform configuration</CardDescription>
              </div>
              {generatedCode && (
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={copyToClipboard}>
                    <Copy className="h-4 w-4" />
                  </Button>
                  <Button variant="outline" size="sm" onClick={downloadFile}>
                    <Download className="h-4 w-4" />
                  </Button>
                </div>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {generatedCode ? (
              <pre className="h-[600px] overflow-auto rounded-lg bg-secondary p-4 text-xs">
                <code>{generatedCode}</code>
              </pre>
            ) : (
              <div className="flex h-[600px] items-center justify-center rounded-lg border-2 border-dashed border-border">
                <p className="text-muted-foreground">Configure and generate your Terraform code</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Usage Instructions */}
      <Card>
        <CardHeader>
          <CardTitle>Usage Instructions</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <Badge className="mb-2">Step 1</Badge>
            <p className="text-sm text-muted-foreground">
              Download the generated <code className="rounded bg-secondary px-1 py-0.5">main.tf</code> file
            </p>
          </div>
          <div>
            <Badge className="mb-2">Step 2</Badge>
            <p className="text-sm text-muted-foreground">
              Initialize Terraform: <code className="rounded bg-secondary px-1 py-0.5">terraform init</code>
            </p>
          </div>
          <div>
            <Badge className="mb-2">Step 3</Badge>
            <p className="text-sm text-muted-foreground">
              Review the plan: <code className="rounded bg-secondary px-1 py-0.5">terraform plan</code>
            </p>
          </div>
          <div>
            <Badge className="mb-2">Step 4</Badge>
            <p className="text-sm text-muted-foreground">
              Apply the configuration: <code className="rounded bg-secondary px-1 py-0.5">terraform apply</code>
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
